# Generated by Django 2.2.1 on 2019-11-24 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_summary', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('date_published', models.DateTimeField(default=datetime.datetime(2019, 11, 24, 17, 29, 13, 677471), verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
