# Generated by Django 2.2.1 on 2019-11-24 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191124_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 17, 30, 40, 622823), verbose_name='date published'),
        ),
    ]
