# Generated by Django 2.2.1 on 2019-11-24 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191124_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 21, 30, 2, 897250), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
