# Generated by Django 2.2.1 on 2019-11-24 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191124_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 21, 42, 50, 271004), verbose_name='date published'),
        ),
    ]
