# Generated by Django 2.2.1 on 2019-11-24 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191124_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preview_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 21, 43, 30, 213230), verbose_name='date published'),
        ),
    ]
