# Generated by Django 3.0.3 on 2020-08-26 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191124_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 11, 29, 52, 249080), verbose_name='date published'),
        ),
    ]
