# Generated by Django 3.0.3 on 2020-09-11 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200911_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 10, 54, 7, 726745), verbose_name='date published'),
        ),
    ]
