# Generated by Django 3.0.3 on 2020-09-11 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200911_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 20, 43, 26, 545771), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(default='static/images/default_image.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
