# Generated by Django 3.0.3 on 2020-09-12 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200911_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='content_DE',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content_EN',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content_PT',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_DE',
            field=models.CharField(default='', max_length=511),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_EN',
            field=models.CharField(default='', max_length=511),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_PT',
            field=models.CharField(default='', max_length=511),
        ),
        migrations.AddField(
            model_name='post',
            name='title_DE',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title_EN',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title_PT',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 21, 13, 27, 967542), verbose_name='date published'),
        ),
    ]
